version: '3.8'

services:
  web:
    build: .
    image: tu_usuario/php-sample-app:latest
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
